---
title: "Questions"
format: html
---

# Exercises -

### 1. Filtering rows

> **Question 1:** Read in the Minnesota tree growth dataset. Use glimpse to understand the structure and names of the dataset. Decribe the structure and what you see in the dataset?
>
> -   The columns are seperated into the tree ID numbers, the stand ID, the stand, year, species, age, inc, and read_ib. There is about 131,386 rows of data.
>
> **Question 2:** How many records have been made in standID 1?
>
> -   979
>
> **Question 3:** How many records of the Abies balsamea and Pinus strobus species have been made?
>
> -   13033 Abies balsamea
>
> -   4188 Pinus strobus
>
> **Question 4:** How many trees are older then 200 years old in the last year of the dataset?
>
> -   7

### 2. Slicing Rows

> **Question 5: What is the oldest tree in the dataset found using slice_max?**
>
> -   269

> **Question 6: Find the oldest 5 trees recorded in 2001. Use the help docs to understand optional parameters**
>
> -   263, 259, 212, 206, 206

> **Question 7: Using slice_sample, how many trees are in a 30% sample of those recorded in 2002?**
>
> -   727

### 3. Arranging Rows

> **Question 8: Filter all trees in stand 5 in 2007. Sort this subset by *descending* radius at breast height (rad_ib) and use slice_head() to get the top three trees. Report the tree IDs**
>
> -   128, 157, 135

### 4. Reducing Columns

> **Question 9: Reduce your full `data.frame` to \[treeID, stand, year, and radius at breast height\]. Filter to only those in stand 3 with records from 2007, and use slice_min to pull the smallest three trees meaured that year.**
>
> -   50, 56, 36

> **Question 10: Use select to *remove* the stand column. Use glimspe to show the dataset.**
>
> -   Done

> **Question 11: Look at the help document for dplyr::select and examine the “Overview of selection features”. Identify an option (there are multiple) that would help select all columns with the string “ID” in the name. Using glimpse to view the remaining dataset**
>
> -   Done, used "contains("ID")"
>
> **Question 12: Find a selection pattern that captures all columns with either ‘ID’ or ‘stand’ in the name. Use glimpse to verify the selection.**
>
> -   

### 5. Renaming Columns

> **Question 13: Looking back at the data dictionary, rename rad_inc and inc to include `_[unit]` in the name. Unlike earlier options, be sure that this renaming is permanent, and stays with your data.frame (e.g. `<-`). Use glimpse to view your new data.frame.**
>
> -   Done!

### 6. Creating New Columns

> **Question 14: A key measurement in forestry in “basal area column”. The metric is computed with the formula:\
> BA(m2) = 0.00007854⋅DBH\^2\
> Where DBH is the diameter at breast height (cm). Use mutate to compute DBH in centimeters, and BA in m2 (HINT: Make sure rad_ib is in cm prior to computing the diameter!). What is the mean BA_m2 of the the species `POTR` in 2007?**
>
> ```         
>  0.009241546
> ```

### 7. case_when / if_else

> **Question 15: Lets say for the sake of our study, trees are not established until they are 5 years of age. Use `if_else` to add a boolean column to our dataset called `established` that is TRUE if the age is greater then 5 and FALSE if less then or equal to five. Once added, use count (see ?count) to determine how many records are from estabilshed trees?**
>
> -   122,503 established \| 8,883 young
>
> **Question 16: Use `mutate` and `case_when` to add a new column to you data.frame that classifies each tree into the proper DBH_class. Once done, limit your dataset to the year 2007 and report the number of each class with count.**
>
> -   473 pole, 1817 sapling, 1 sawlog

### 8. Summarizing

> **Question 17: Compute the mean DBH (in cm) and standard deviation of DBH (in cm) for all trees in 2007. Explain the values you found and their statistical meaning.**
>
> -   mean: 8.046755 - the sum of all the DBH divided by the number of observations to find the "average"
>
> -   sd: 3.069321 - finds the amount of variation from the mean value

### 9. Grouped Data

> **Question 18: Compute the *per species* mean tree age using only those ages recorded in 2003. Identify the three species with the oldest mean age.**
>
> -   THOC (126.63830), FRNI (83.08333), PIST (73.28571)

### 10. Counting

> **Question 19: In a single summarize call, find the number of unique years with records in the data set along with the first and last year recorded?**
>
> -   Unique Years: 111
>
> -   1st Year: 1897
>
> -   Last Year: 2007
>
> **Question 20: Determine the stands with the largest number of unique years recorded. Report all stands with largest (or tied with the largest) temporal record.**
>
> -   A1, D1, D2, D3, F1

### Final Question

> **Use a combination of dplyr verbs to compute these values and report the 3 species with the fastest growth, and the 3 species with the slowest growth. (\*\* You will need to use either `lag()` or `diff()` in your compuation. You can learn more about each in the Help pages)**
>
> **Lastly, find and include an image of the fastest growing species. Add the image to your images directory.**
>
> -   Fastest growing trees: PIRE (0.0221793750), PIST (0.0133043457), and POTR (0.0120377590)
>
> -   Slowest growing trees: ABBA (-0.0197856392), PIGL (-0.0107553007), ACRU (-0.0053966451)
